### ISSUE TITLE
Execv failed (no such file or directoy)

### ISSUE THREAD

**Issue by Arindamname** [sdrausty/termux-arch#2]
Execv failed always comes up while installing any package and also during installation in armhf

**Comment by sdrausty** [comment]
Details are requested.  Post your input and output along with system information.  Use `setupTermuxArch.sh --sysinfo` to provide system information.

**Comment by Arindamname** [comment]
Thats i am getting after installing any package like I ran pacman -S nmap, after the installation it gives following error:
call to execv failed (No such file or directory) error: command failed to execute correctly       :: Running post-transaction hooks...             (1/2) Arming ConditionNeedsUpdate...             call to execv failed (No such file or directory) error: command failed to execute correctly       (2/2) Updating the desktop file MIME type cache...                                                call to execv failed (No such file or directory) error: command failed to execute correctly
And your commnand setupTermuxArch.sh --sysinfo isn't working( command not found)

**Comment by sdrausty** [comment]
@Arindamname more information is wanted to better understand this issue.  There is no error like this on aarch64 and armv7.  Use `bash setupTermuxArch.sh sysinfo` to give the information that was requested.  
> along with system information.  

Use `termux-info` too.  More information about the device architecture is wanted to turn puzzle into a potential resolution.  Do not hesitate to add screenshots.
```
!!
pacman -S nmap
resolving dependencies...
looking for conflicting packages...

Packages (2) lua52-5.2.4-2  nmap-7.60-1

Total Installed Size:  27.48 MiB

:: Proceed with installation? [Y/n]
(2/2) checking keys in keyring                         [############################] 100%
(2/2) checking package integrity                       [############################] 100%
(2/2) loading package files                            [############################] 100%
(2/2) checking for file conflicts                      [############################] 100%
(2/2) checking available disk space                    [############################] 100%
:: Processing package changes...
(1/2) installing lua52                                 [############################] 100%
(2/2) installing nmap                                  [############################] 100%
Optional dependencies for nmap
    pygtk: zenmap
    sudo: privilege escalation for zenmap
    xterm: privilege escalation for zenmap
    kde-cli-tools: privilege escalation for zenmap
    gksu: privilege escalation for zenmap
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[04:12 home ]$ namp --version
bash: namp: command not found
[04:12 home ]$ nmap --version

Nmap version 7.60 ( https://nmap.org )
Platform: armv7l-unknown-linux-gnueabihf
Compiled with: nmap-liblua-5.3.3 openssl-1.1.0f libssh2-1.8.0 libz-1.2.8 libpcre-8.41 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
[04:12 home ]$ nmap --help
Nmap 7.60 ( https://nmap.org )
Usage: nmap [Scan Type(s)] [Options] {target specification}
TARGET SPECIFICATION:
  Can pass hostnames, IP addresses, networks, etc.
```
The exec error origin is unkown.  Providing the device architecture (include the Arch Linux system image download name) to help turn a puzzle into a possible resolution.

**Comment by jlebonzec** [comment]
Hello!

Since this issue comes second when searching for "_archlinux execv not found_", Here's the solution that worked for me, even though it is unrelated to this repository:

```bash
sudo pacman -S pacman-contrib
```

Remember: don't do partial upgrades, and upgrade more often.

I hope that helps some people.


PS: If it annoys you, feel free to remove the comment even without telling me, @sdrausty. :)

**Comment by sdrausty** [comment]
Hi @jlebonzec 
> Since this issue comes second 

Link?

**Comment by SDRausty** [comment]
This [commit](https://github.com/SDRausty/termux-arch/commit/7a5e648ca0d8705e4e800a98f9e31850cde605bc) adds support for `pacman-contrib` in all available architectures.  Thank you for sharing @jlebonzec 🔔
