### ISSUE TITLE
new feature suggestion based on Exagear for Termux

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-arch#8]
Dear Mr Rausty,
I Am kindly suggesting you to add new possibility to run X86 apps by using Termux and Proot. Feature is not based on slow and problematic Qemu emulation. So you could add this possibility as a concurrent to Proot and Qemu emulation.
Try to analyse this machine code module on Github.

https://github.com/ZhymabekRoman/Exagear-For-Termux

Repository contain Bash script and some small binary module. I have tested it according to The authors example. And it have been faster than Qemu emulation. Sure, not so fast like The execution of Architecture compatible machine code on real device.
But it would be good alternative to Qemu emulation.
Please try to look at this.

There are some issues related to socket communication, so may be, that full desktops can not be executed by using this project. But I think, that it will be good project for every one who would like to build The packages by using cross compilation.

Unfortunately, I can not find The source code of binary data. If The author has even used Assemlber language.
Author is very smart, he has even made shared memory emulation in Proot for Termux. So I think, that it will be also good idea from him to develop Exagear for Termux.

**Comment by SDRausty** [comment]
>develop Exagear for Termux.

Thank you for suggesting [Exagear](https://github.com/ZhymabekRoman/Exagear-For-Termux).  This might be a great idea.  I cannot develop at Termux presently as my account is blocked by [rouge Termux curators](https://github.com/SDRausty/builtAPKs/issues/2) once again.

**Comment by SDRausty** [comment]
>can not find The source code of binary data.

**Comment by SDRausty** [comment]
I am still awaiting habitual success results with [`makelibguestfs`](https://github.com/SDRausty/termux-arch/blob/master/archlinuxconfig.bash#L715&&#L937) and being able to mount partitions.

**Comment by SDRausty** [comment]
>Unfortunately, I can not find The source code of binary data.

When it is found, thís issue can be continued.
